### PR TITLE
allow check_default_data_path to use different messaging functions

### PR DESCRIPTION
**Pull request by ha0ye**

### CODE REVIEW

**Comment by ha0ye** [comment]
closes #194

**Comment by juniperlsimonis** [comment]
some character didn't render right
image

also, the message makes it seem like i could just run `use_default_data_path("~")` or whatever and it would set it up, but when i run that i get a list of instructions that i have to follow including a restart of R. I personally totally understand that, but putting myself in the shoes of a naive user of the package, I'm wondering why I need to do all that. 

So I guess my thought would be "is there a way that the default path can get set up without needing the user to do those steps? then if a user wants to change it, they can by following those steps?"

**Comment by ha0ye** [comment]
We can write out to the .Renviron file, but this workflow seems to be what the `usethis` package uses... It may be safer this way instead of possibly mucking up a user's .Renviron file automatically?

**Comment by juniperlsimonis** [comment]
yeah no totally not suggesting to automatically edit the .Renviron file, but rather to make a default assumption about the location of the data if that file doesn't have an entry...or something like that?

**Comment by ha0ye** [comment]
It will still use "~" as the default if it's not set. Do you think the startup message needs to be edited a bit?

**Comment by juniperlsimonis** [comment]
ah! then yes, if it will default to using "~" and everything works fine if you don't change it, then the message should be edited. the exclamation point certainly makes it seem like a critical thing to me.
maybe cut that punctuation (put a period if you feel it needs something), have a statement like "default data path is "~"" and then change the "Call ... to set a default data path" to "Call ... if you wish to change the default data path"

**Comment by ha0ye** [comment]
:+1: Do you want to add a commit to this branch or should I?

**Comment by juniperlsimonis** [comment]
i'm not sure offhand where i would jump in to make those edits, so since you're familiar with it, i'd default to you doing it if you can.

**Comment by juniperlsimonis** [comment]
sorry i forgot to tick approve!

**Pull request merged**
