### PR TITLE
fix NDVI cleaning

### PR DESCRIPTION
**Pull request by sdtaylor**
This was causing an error with new NDVI data. It's no longer needed now that the full GIMMS NDVI has been implemented in PortalData.

Don't merge until https://github.com/weecology/PortalData/pull/168 has been merged.

### CODE REVIEW

**Comment by sdtaylor** [comment]
can someone restart the test now that https://github.com/weecology/PortalData/pull/168 is merged?

**Comment by skmorgane** [comment]
I've merged Ethan's version because it also dealt with a column name change and updated a test on that output. My reading is that this pull request can be deleted?

**Comment by skmorgane** [comment]
Ethan explained that I should handle this by explaining why I merged his and not yours and then close this myself. So I'm closing!

**Comment by sdtaylor** [comment]
as long as it works in the end :+1: :smile:

**Pull request closed without merging**
