### PR TITLE
Plant summaries: add na_drop and zero_drop

### PR DESCRIPTION
**Pull request by emchristensen**
this involved a pretty major refactor of get_plant_data. I modeled it after the rodent version (get_data).

### CODE REVIEW

**Comment by bleds22e** [comment]
Would these changes make the tests fail, maybe?

**Comment by emchristensen** [comment]
My refactored code is having a problem with plot 24 quadrat 17 (the one that was outside the fence 2004-2014). However, apparently people still counted plants in this quadrat in summer 2004 and winter 2005 (there's count data in Portal_plant_quadrats.csv but the quadrat is indicated as not censused in Portal_plant_censuses.csv). Should I 1) deal with it at the data level (i.e. flag these rows as suspect in the notes column of Portal_plant_quadrats.csv) or 2) find a way to filter those out using Portal_plant_censuses.csv? @gmyenni @bleds22e @ha0ye

**Comment by bleds22e** [comment]
I'm inclined to add flags to them in the csv and filter them out that way, but I'm not tied to that

**Comment by ha0ye** [comment]
I like @bleds22e ‘s suggestion, as someone would be able to look up what happened to the data in the metadata, but I’m not tied to any particular solution either.

**Comment by emchristensen** [comment]
There's now a pull request in PortalData with those changes. This probably won't pass until that's merged.

**Pull request merged**
