### PR TITLE
Use right location for RStudio package manager in R CMD check build

### PR DESCRIPTION
**Pull request by ethanwhite**

### CODE REVIEW

**Comment by ethanwhite** [comment]
Thus illustrating the value of cross-project code review :smile:

**Comment by gmyenni** [comment]
Ah! But the same failure is still happening. 🤔

**Comment by ethanwhite** [comment]
Can you link the documentation for using the `RSPM` environment variable the way you're doing it? I wonder if that's available in `devel` but not `release`?

**Comment by gmyenni** [comment]
https://github.com/r-lib/actions/blob/master/.github/workflows/check-standard.yaml

There isn't really much documentation. 

It seems weird that it would be an issue with the R release version, since this was all working fine until last week.

**Comment by gmyenni** [comment]
Fyi, I tried updating some details to match https://github.com/tidyverse/dplyr/blob/master/.github/workflows/R-CMD-check.yaml , which passed 6 hours ago. 🤷‍♀️  I also tried reverting to 16.04, which they still use in dplyr, but that didn't help either.

**Comment by gmyenni** [comment]
Okay, after @henrykironde and I tried every possible thing, this does seem to legitimately be an issue with R 4.0.4. Since devel is passing, we're just going to use 4.0.3 for now, which also passes.

**Pull request closed without merging**
