### PR TITLE
add documents for joss paper submission: portalr.md and paper.bib

### PR DESCRIPTION
**Pull request by emchristensen**

### CODE REVIEW

**Comment by emchristensen** [comment]
still needed: author information, and link to documentation on CRAN when that happens

**Comment by emchristensen** [comment]
Yep: same author order? But with me first?

**Comment by emchristensen** [comment]
Oh, and I wasn't sure if we needed an acknowledgements section: acknowledge funding agencies? Who funded this?

**Comment by ha0ye** [comment]
> Oh, and I wasn't sure if we needed an acknowledgements section: acknowledge funding agencies? Who funded this?

Should be similar to the portal forecasting papers, but I would put your funding first, then Morgan's, then Ethan's.

**Pull request merged**
