### PR TITLE
Update summarize_plants.R

### PR DESCRIPTION
**Pull request by diazrenata**
You can get negative shrub cover values for some (post-2015) transects, because those transects' stop values are truncated at 7071, but some of their start values are also above 7071. So if you have a shrub where both stop and start are > 7071, **stop** gets truncated to 7071 but **start** remains > 7071, and stop-start is negative. Filtering so start > 7071 removes all shrubs that occur entirely beyond 7071.

### CODE REVIEW

**Comment by gmyenni** [comment]
Is this still a work in progress?

**Comment by diazrenata** [comment]
It was just the single line change. I think tests are failing because of
something further upstream?

**Comment by gmyenni** [comment]
Can you merge in main and rerun the tests? They should pass.

**Comment by gmyenni** [comment]
Thanks @diazrenata looks good!

**Pull request merged**
