### PR TITLE
Biomass function

### LINKED ISSUE #1: Write biomass function
It should start with the raw data and have similar options to [RodentAbundances.R](https://github.com/weecology/PortalDataSummaries/blob/master/RodentAbundances.R) but return either biomass or energy.

### PR DESCRIPTION
**Pull request by ha0ye**
piggybacking off of work that @diazrenata already did:
* to not have redundant code, I made a general function to summarize either abundance or biomass; the `abundance` and `biomass` function are just specific instances of that
* some changes to `make_crosstab` to get it to work
* smoothed out the documentation a bit

NOTES:
You may notice that in some instances, biomass = 0, and in others, biomass = NA. This seems to be due to the original data not having biomass measured in each case. So when there is an animal, but no measures, the sum gets converted to 0, but if there were no sightings, biomass = NA.

The ideal is if `dplyr::group_by` did not drop empty combinations, but this apparently has been an issue since 2014 (https://github.com/tidyverse/dplyr/issues/341). Other options are to use tidyr::complete to create empty groups that will then have 0 biomass even if no animals were sighted. We can then inform users to compare biomass against abundance if they want to see about animals that were not weighted.

EDIT:
closes #1

### CODE REVIEW

**Comment by gmyenni** [comment]
The way that I (and I think others) have dealt with missing weight data when summing biomass is to (ideally) fill it in with the nearest observed weight from that individual, or (if the individual was only captured once) mean weight for that species (mean adult weight, or juvenile weight if individual was marked as juvenile).

**Comment by ha0ye** [comment]
Hmm - ok. That will make things more complicated, but I'll take a look.

**Comment by gmyenni** [comment]
The [species list](https://github.com/weecology/PortalData/blob/master/Rodents/Portal_rodent_species.csv) has mean body sizes now. So that can be used to estimate missing biomass.

**Comment by ha0ye** [comment]
Shoot, I forgot about this. Ok, adding `portalr` back on to my TODO list...

**Comment by skmorgane** [comment]
What's the status of this PR? If it ready to be reviewed?

**Comment by ha0ye** [comment]
@skmorgane Right now, the code in the PR ignores NAs in the biomass data. If that's fine for now, it can be reviewed and merged (I don't think it will break anything in PortalPredictions).

Do you think the default for biomass calcs should impute average biomass for missing data? We could also add an additional argument that switches between imputing and ignoring NAs.

(Personally, I'm not sure if there are potential biases in NA values, which would be a reason to NOT ignore NAs, under presumption that biomass and abundance should be computed off of the same data points.)

**Comment by diazrenata** [comment]
I think it doesn't do energy yet either. I was going to work on this a little more, but I don't want to duplicate Hao's effort...So I think if we merge this one, and then I start working based on an updated master, that would work? (I am not sure about the ideal workflow - is there a preferable way? Can I somehow get a copy of this pull request without merging it to the master?)

**Comment by ha0ye** [comment]
Let me make a new branch under the weecology repo, and PR into there, and then @diazrenata, you'll be able to work off that one.

**Comment by ha0ye** [comment]
Ok, I'm going to close this PR, and let the changes happen in the weecology:biomass-function branch. @diazrenata, you should have access to pull and push changes to that one.

**Pull request closed without merging**
